#!/usr/bin/env bash

# Default parameters
threads=$(command -v nproc --all &> /dev/null && nproc || echo 1)
gfftype="mRNA"

# Cleanup temp files
tmpdir=$(mktemp --tmpdir=/tmp --directory annopipe.XXXXXXXXXX)
chmod --recursive 775 $tmpdir
cleanup(){
 rm --force --recursive $tmpdir
}
trap cleanup EXIT

function print_usage(){
 printf "Perform functional annotation of a genome, given a FASTA file and a GFF3/GTF file

annopipe [OPTIONS] [-n Name] [-g Sequence.fasta] [-f Sequence.gff3|Sequence.gtf] [-o outdir]
	-n | --name # Name of the run
	-g | --genome # Genome FASTA file
	-f | --gtff # Structural annotation file in gtf/gff3 format
	-o | --outdir # Output directory (Default = Name_annopipe)
        -e | --egg # Annotation file produced by EggnogMapper (use '--egg path_to_file' for egg2gbk only OR '--egg 0' to get the file from annopipe)
        -b | --braker   Run Braker
        --rm_con   RepeatModeler consensi file (consensi.fa.classified) for Braker
        --bam      Path to BAM files (RNAseq) for Braker
        -p | --prot # Proteome file (for egg2gbk)
        -s | --species # Full species name (e.g. \"Arabidopsis thaliana\") (for egg2gbk)
	-r | --run # Analyses to run (swissprot_blastp,swissprot_blastx,pfam,signalp6,tmhmmv2,infernal,EggnogMapper; run all with '--run 0')
	-gt | --gff-type # Type of GFF CDS retrieval passed to emapper2gbk (see README)
	-c | --patho # Create Pathway tools database using Pathologic
	-k | --keep # Keep all temp files in outdir
	-t | --threads #	Number of CPU threads to use (Default = Detected processors or 1)
	-h | --help # Print help
	
	Example: annopipe --threads 32 --name A.thaliana --genome TAIR10_genome.fa --gtff TAIR10.gff3 --egg 0 --run swissprot_blastp,swissprot_blastx,EggnogMapper --outdir At_trinotate
	
"
}

while [ "$#" -gt 0 ]
do
arg="$1"
 case $arg in
  -n | --name)
  Name="$2" # Run name
  shift 2
  ;;
  -g | --genome)
  genome=$(readlink -f "$2") # genome FASTA file path
  shift 2
  ;;
  -f | --gtff)
  gtff=$(readlink -f "$2") # gtf/gff3 file path
  shift 2
  ;;
  -o | --outdir)
  outdir=$(readlink -f "$2") # output directory
  shift 2
  ;;
  -e | --egg)
  egg="$2" # Eggnog annotation file
  shift 2
  ;;
  -b | --braker)
  braker=1 # Run Braker
  shift 1
  ;;
  --rm_con)
  rm_con=$(readlink -f "$2") # RM file
  shift 2
  ;;
  --bam)
  bam=$(readlink -f "$2") # BAM RNAseq files
  shift 2
  ;;
  -p | --prot)
  prot=$(readlink -f "$2") # Protein file
  shift 2
  ;;
  -s | --species)
  species="$2" # Species
  shift 2
  ;;
  -r | --run)
  OFS=$IFS
  IFS=","
  run=($(echo "$2"))
  IFS=$OFS
  shift 2
  ;;
  -gt | --gff-type)
  gfftype="$2"
  shift 2
  ;;
  -c | --patho)
  patho=1
  shift 1
  ;;
  -k | --keep)
  shift 1
  ;;  
  -t | --threads)
  threads=$2 # Threads
  shift 2
  ;;
  -h | --help)
  print_usage
  exit 1
  ;;
  *)
  if [ -f "$1" ]
  then
   break
  else
  echo "Unknown option: "$1
  print_usage
  exit 1
  fi
  ;;
  esac
 done
 
 # Check dependencies
  if ! command -v braker.pl &> /dev/null && [ ! -z ${braker+x} ]
  then
   echo "braker not installed" >&2
   echo "https://github.com/Gaius-Augustus/BRAKER" >&2
   deps+="braker"
  fi
  
  if ! command -v emapper2gbk &> /dev/null && [ ! -z ${egg+x} ]
  then
   echo "emapper2gbk not installed" >&2
   echo "https://github.com/AuReMe/emapper2gbk" >&2
   deps+="emapper2gbk"
  fi
  
  if ! command -v gt &> /dev/null
  then
   echo "genometools not installed" >&2
   echo "sudo apt install genometools" >&2
   deps+="genometools"
  fi
  
  if ! command -v Trinotate &> /dev/null && [ ! -z ${run+x} ]
  then
   echo "Trinotate not installed" >&2
   echo "https://github.com/Trinotate/Trinotate" >&2
   deps+="Trinotate"
  fi

  if ! command -v mpwt &> /dev/null && [ ! -z ${egg+x} ]
  then
   echo "mpwt not installed" >&2
   echo "https://github.com/AuReMe/mpwt" >&2
   deps+="mpwt"
  fi
  
  if [ ! -z ${deps+x} ]
  then
   exit 1
  fi
  
  if [ ! -z ${run+x} ] || [ ! -z ${egg+x} ]
  then
  if [ -z ${genome+x} ]
  then
   echo "Must designate genome file with -g | --genome" >&2
   exit 1
  fi
  
  if [ -z ${gtff+x} ] || [ ! -z ${braker+x} ]
  then
   echo "Must designate structural annotation file with -f | --gtff" >&2
   exit 1
  fi
  fi
   
  if [ -z ${Name+x} ]
  then
   echo "Must designate name with -n | --name" >&2
   exit 1
  fi
  
if [[ ${run[@]-x} =~ "0" ]]
then
 run=(swissprot_blastp swissprot_blastx pfam signalp6 tmhmmv2 infernal EggnogMapper)
fi

if [ ! -z ${TRINOTATE_DATA_DIR+x} ]
then
 rm -f $TRINOTATE_DATA_DIR"/__chckpts/cp_trinotate_boilerplate_sqlite_to_"$Name".sqlite.ok"
 gobo=$TRINOTATE_DATA_DIR"/go-basic.obo"
else
 wget -O $tmpdir http://purl.obolibrary.org/obo/go/go-basic.obo
 gobo=$tmpdir"/go-basic.obo"
fi

if [ -z ${outdir+x} ]
then
 outdir=$(pwd)"/"$Name"_annopipe"
fi

if [ ! -d $outdir ]
then
 mkdir --parents $outdir
fi

if [ ! -z ${egg+x} ] && [ -z ${species+x} ]
then
 echo "Please specify a species with '-s | --species'" >2&
 exit 1
fi

if [ ! -z ${egg+x} ] && [[ $egg == "0" ]] && [ ! -z ${run+x} ] && [[ ! ${run[@]} =~ "EggnogMapper" ]]
then
 run+="EggnogMapper"
fi

if [ ! -z ${braker+x} ] && [ -z ${species+x} ]
then
pl_script=$(mktemp --tmpdir=$tmpdir annopipe.XXXXXXXXXX)
echo -e '#!/usr/bin/perl -w\nuse strict;\nmy @cols;\nmy $new_nine;\nwhile (<>) {\n        chomp;\n        @cols = split /\\t/, $_;\n        $new_nine=$cols[8];\n        if ($cols[2]eq"gene") {\n                $new_nine="gene_id \\"$cols[8]\\"";\n        } elsif ($cols[2]eq"transcript") {\n                $new_nine="transcript_id \"$cols[8]\"";\n        }\n        print join "\\t", $cols[0],$cols[1],$cols[2],$cols[3],$cols[4],$cols[5],$cols[6],$cols[7],$new_nine;\n        print "\\n";\n}' > $pl_script

braker.pl \
--species="${species/ /_}" \
--useexisting \
--softmasking \
--genome=$genome \
--bam=$(find $bam -name "*bam" | tr "\n" "," | sed -E 's/,$//g') \
--workingdir=$tmpdir/braker_out \
--threads $threads

perl $pl_script < $tmpdir/braker_out/braker.gtf |
if [ $(head $tmpdir/braker_out/braker.gtf | grep -cP "file_[0-9]") -gt 0 ]
then
 sed -E 's/file_[0-9]+_file_[0-9]+_//g'
else
 cat
fi |
tee $tmpdir/braker_out/braker_fixed.gtf |
grep -P "\tCDS\t|\texon\t" |
gt gtf_to_gff3 |
grep -vP "^###$" > $tmpdir/braker_out/braker.gff3
cat <(grep "#" $tmpdir/braker_out/braker.gff3) <(grep -v "#" $tmpdir/braker_out/braker.gff3 | awk -F $'\t' '{OFS="\t"};
{gene=gensub(/.*gene_id=([^;]+).*/,"\\1","G",$9);
trans=gensub(/.*transcript_id=([^;]+).*/,"\\1","G",$9)};
$3 ~ /gene/{print $1,$2,$3,$4,$5,$6,$7,$8,"ID="gene}
$3 ~ /mRNA/{print $1,$2,$3,$4,$5,$6,$7,$8,"ID="trans";Parent="gene}
$3 ~ /CDS|exon/{print $1,$2,$3,$4,$5,$6,$7,$8,"ID="trans";Parent="trans}
$3 !~ /gene|mRNA|transcript|CDS|exon/{print $0}') \
> $tmpdir/braker_out/braker_fixed.gff3

cp --force $tmpdir/braker_out/braker_fixed.gtf $outdir"/"$Name".gtf"
cp --force $tmpdir/braker_out/braker_fixed.gff3 $outdir"/"$Name".gff3"

gtff=$outdir"/"$Name".gff3"
fi

if [ ! -z ${run+x} ]
then

cd $tmpdir

if [[ ${gtff##*.} == "gff" ]]
then
 cp --force $gtff $tmpdir"/"$gtff"3"
 gtff=$tmpdir"/"$gtff"3"
fi

Trinotate --create \
--db $tmpdir"/"$Name.sqlite \
--use_diamond

Trinotate_GTF_or_GFF3_annot_prep.pl \
--annot $gtff \
--genome_fa $genome \
--out_prefix $tmpdir"/"$Name

[ -f $tmpdir"/"$Name".proteins.fa" ] && cp --force $tmpdir"/"$Name".proteins.fa" $outdir

if [ -z ${prot+x} ]
then
 prot=$tmpdir"/"$Name.proteins.fa
fi

Trinotate --init \
--db $tmpdir"/"$Name.sqlite \
--gene_trans_map $tmpdir"/"$Name.gene-to-trans-map \
--transcript_fasta $tmpdir"/"$Name.transcripts.cdna.fa \
--transdecoder_pep $tmpdir"/"$Name.proteins.fa

Trinotate \
--db $tmpdir"/"$Name.sqlite \
--CPU $threads \
--transcript_fasta $tmpdir"/"$Name.transcripts.cdna.fa \
--transdecoder_pep $tmpdir"/"$Name.proteins.fa \
--run "${run[*]}" \
--use_diamond

[ -f $tmpdir"/eggnog_mapper.emapper.annotations" ] && cp --force $tmpdir"/eggnog_mapper.emapper.annotations" $outdir

if [[ $egg == "0" ]]
then
 egg=$tmpdir"/eggnog_mapper.emapper.annotations"
fi

if [[ ${run[@]} =~ "swissprot_blastp" ]] || [[ ${run[@]} =~ "swissprot_blastx" ]]
then
 Trinotate --report \
 --db $tmpdir"/"$Name.sqlite \
 > $outdir"/"$Name"_report.tsv"

 extract_GO_assignments_from_Trinotate_xls.pl \
 --Trinotate_xls $outdir"/"$Name"_report.tsv" \
 -G \
 --include_ancestral_terms \
 > $tmpdir"/"$Name"_GO_output"
 
 grep --word-regexp --invert-match -f <(cut --fields=1 $tmpdir"/"$Name"_GO_output" | sort --unique) <(cut -f1 $Name".gene-to-trans-map") |
 sort > $outdir"/"$Name"_GO_mapping"
  
fi
fi

if [ ! -z ${egg+x} ]
then
 if [[ ${gtff##*.} == "gtf" ]]
 then
  tmp_gff=$(mktemp --tmpdir=$tmpdir annopipe.XXXXXXXXXX)
  tmp_comments=$(mktemp --tmpdir=$tmpdir annopipe.XXXXXXXXXX)
  gt gtf_to_gff3 $gtff |
  grep -vP "^###$" > $tmp_comments
  cat <(grep "#" $tmp_comments) <(grep -v "#" $tmp_comments | awk -F $'\t' '{OFS="\t"};
  {gene=gensub(/.*gene_id=([^;]+).*/,"\\1","G",$9);
  trans=gensub(/.*transcript_id=([^;]+).*/,"\\1","G",$9)};
  $3 ~ /gene/{print $1,$2,$3,$4,$5,$6,$7,$8,"ID="gene}
  $3 ~ /mRNA/{print $1,$2,$3,$4,$5,$6,$7,$8,"ID="trans";Parent="gene}
  $3 ~ /CDS|exon/{print $1,$2,$3,$4,$5,$6,$7,$8,"ID="trans";Parent="trans}
  $3 !~ /gene|mRNA|transcript|CDS|exon/{print $0}') \
  > $tmp_gff
  gtff=$tmp_gff
 fi
 
 tmp_prot=$(mktemp --tmpdir=$tmpdir annopipe.XXXXXXXXXX)
 sed -E 's/(>[^.]+)[.]pep.*/\1/g' $prot > $tmp_prot
 prot=$tmp_prot
 
 tmp_egg=$(mktemp --tmpdir=$tmpdir annopipe.XXXXXXXXXX)
 sed -E 's/[.]pep\t/\t/g' $egg > $tmp_egg
 egg=$tmp_egg
 
 emapper2gbk genomes \
 --fastanucleic $genome \
 --fastaprot $prot \
 --gff $gtff \
 --name "$species" \
 --out $outdir"/"$Name.gbk \
 --annotation $egg \
 --cpu $threads \
 --gobasic $gobo \
 --gff-type $gfftype
fi

if [ ! -z ${patho+x} ]
then
 mkdir --parents $tmpdir"/pgdb/"$Name
 ln -s $outdir"/"$Name".gbk" $tmpdir"/pgdb/"$Name"/"
 mpwt \
 -f=$tmpdir"/pgdb" \
 -o=$tmpdir \
 --hf \
 --tp \
 --cp \
 --patho \
 --clean \
 --cpu $threads \
 -v
fi

if [ ! -z $keep ]
then
 mv --force $tmpdir $outdir
fi
